### ISSUE TITLE
Microsecond timer

### ISSUE THREAD

**Issue by hodiapa** [pabigot/bsp430#19]
Enhancements/Feature Request:
- Can we have a microsecond timer support in the msp430 library.
- RTC/Timer library. 
- Similar to tinyos can we have a oneshot timer/alarm support.

**Comment by pabigot** [comment]
```
Can we have a microsecond timer support in the msp430 library.
```

Yes, with conditions.  BSP430 isn't going to provide a specific microsecond timer, but it will provide infrastructure to use the compare registers of a specific timer peripheral to cause interrupts at certain times.  The existing 32-bit timer counter resolution is used, and the HAL has to be enabled to support overflows so that durations longer than the 16-bit wrap-around are supported.  The user application will have to configure a timer to use an available clock (SMCLK, ACLK) with an appropriate divider to produce a microsecond clock.

I've had this working for a couple days, and just pushed the in-progress work to the next branch.  It needs a review, enhanced examples, and improved documentation before it's officially released and the online documentation updated.  See the bsp430/periph/timer.h file for what's there now, and examples/utility/alarms.  That's going to be updated significantly (the one posted only uses the uptime clock, which is 32 kHz).

I've just been playing with 125ns timers on an EXP430F5438 with SMCLK at 8MHz and they seem to behave reasonably.  Understand that the higher resolution the timer, the later (relatively speaking) the interrupt will actually be processed.

```
RTC/Timer library.
```

Probably not.  Since there's only one RTC peripheral per MCU, there's no need for BSP430 to provide a specific HPL: you can just use the standard peripheral registers.  There may be some value-added features like functions to convert from `struct timeval` to the RTC registers and back, but it'll have to wait until I have some reason to work with the RTC module, and might not be worth it if mspgcc is the only toolchain to support standard time-related structures.  For the purposes of closing this issue I'll be rejecting this request; please file another at that time if you really want it.

```
Similar to tinyos can we have a oneshot timer/alarm support.
```

The alarm functionality that's in the next branch fires off an interrupt when the alarm goes off.  The alarm can be rescheduled either within that interrupt, or when the application processes any notification posted by the interrupt.  This provides maximum flexibility without requiring BSP430 to have any specific notion of oneshot and repeated capability.  For example, if you want the period to be constant regardless of whether the alarm was serviced late you can schedule the next alarm based on the time the previous one was scheduled to fire; elsewise you can schedule based on when the interrupt was serviced, or when the application processed the alarm.  Each is appropriate for different applications.

Another improvement over TinyOS timers (as I remember them): if you cancel an alarm, it'll clear the IFG flag so the interrupt won't fire even if the CC register rolled over while you were cancelling it.  This can be done because BSP430 tries to be explicit about whether interrupts may be enabled when API calls are made, and cancellation should be done with interrupts disabled.  The cancel request return code also tells you if the alarm had already been disabled (e.g., you tried cancelling it too late and it had already fired), allowing you to clean up whatever mess resulted without having to guess what had happened.

**Comment by hodiapa** [comment]
Thanks for the detailed explanation.. I really love the way you have done all the abstractions and have made a modularize setup. Excellent work!!  

I do not want to open a new issue but, can we as well have a coding standard/style documentation. I see you have used specific naming-style for functions, structs, etc. eg: vBSP430 where "v" here means a void function,  xBSP430 where 'x' stands for  char \* function, and so on. That way its easy to understand the code.

**Comment by pabigot** [comment]
Thanks.  I suspect the abstractions will make the learning curve for BSP430 high.  Have you done much development with it yet, or are you mostly just looking?  (AFAIK you're the first person other than me to get into it at all.)

For coding style: See http://pabigot.github.com/bsp430/coding.html

**Comment by pabigot** [comment]
This has been integrated into the 20121013 release.  See specifically http://pabigot.github.com/bsp430/group__grp__timer__alarm.html and the example it references.

**Comment by hodiapa** [comment]
I have just started msp430 dev. So was researching for a framework/libraries supporting msp430. Most of the "frameworks" I crossed supported multiple platforms architectures and nothing fine grained to a specific architecture.
I am thinking of actively using the BSP430 library :).

**Comment by hodiapa** [comment]
> I've just been playing with 125ns timers on an EXP430F5438 with SMCLK at 8MHz and they seem to behave reasonably.

I have got the uptime example running on the launchpad which returns 32768 ticks for ulBSP430uptime(). 
Now that I have got the exp430f5529 where do i specify the XT2 clock as clock source (which is 4Mhz) so that one gets the 4M ticks for the ulBSP430uptime() function.

thanks in advance.

**Comment by pabigot** [comment]
The timer clock source can only be ACLK or SMCLK.  You can configure ACLK to source from XT2CLK using [iBSP430clockConfigureACLK_ni](http://pabigot.github.com/bsp430/clock_8h.html#af634a7a6fbaf23e799250ed9a02b7ce4).  I haven't used XT2CLK, so you may have issues; note that the documentation says that [BSP430_CLOCK_NOMINAL_XT2CLK_HZ](http://pabigot.github.com/bsp430/clock_8h.html#a3b4bcc7d7622f7375d88029e96de2230) must be defined (in your bsp_config.h file).

Alternatively you could use SMCLK as the source for either uptime or another timer.

**Comment by hodiapa** [comment]
did following changes. got an error in the  ‘uiBSP430clockACLK_Hz_ni’ function since it returns 'unsigned int'

<code>
//! bs430_config.h
#define BSP430_PLATFORM_BOOT_CONFIGURE_CLOCKS 0
#define BSP430_CLOCK_NOMINAL_XT2CLK_HZ 4194304UL  //! 4Mhz = 4_1024_1024
//!----------------------------------------------
//! main.c
void main()
{
  vBSP430platformInitialize_ni();
//! configures the clock  
  iBSP430clockConfigureACLK_ni(eBSP430clockSRC_XT2CLK);
  ulBSP430clockConfigureMCLK_ni(BSP430_CLOCK_NOMINAL_MCLK_HZ);
  iBSP430clockConfigureSMCLKDividingShift_ni(BSP430_CLOCK_NOMINAL_SMCLK_DIVIDING_SHIFT);
  (void)iBSP430consoleInitialize();
}
Compiler error log:
/bsp430/src/periph/ucs.c: In function ‘uiBSP430clockACLK_Hz_ni’:
/bsp430/src/periph/ucs.c:427:7: error: large integer implicitly truncated to unsigned type [-Werror=overflow]
</code>

**Comment by pabigot** [comment]
Good point.  I never really considered a high frequency clock for ACLK, since a low frequency one is more useful.  You can still do a 4MHz timer using SMCLK, but BSP430 will only support that with SMCLK as a divided MCLK.  You can also configure SMCLK to source from XT2CLK, but there is no BSP430 interface to configure it that way.

**Comment by hodiapa** [comment]
ok. I changed the macro definition to

> #define BSP430_CLOCK_NOMINAL_XT2CLK_HZ (4_1024_1024U)

and didn't get any errors. And my uptimer count for every second increments by 8066215. which is approximately 8Mhz or 125ns/tick. This is what I wanted to achieve. But I thought I will get around 250ns/tick or 4Mhz counter for the uptimer. Btw I am using the template/console app for checking the accuracy.

**Comment by pabigot** [comment]
Regarding the comment that the XT2 clock appeared to be 8MHz: If XT2 is faulted, any clock that is configured to source from it will fall back to DCOCLKDIV, which is generally around 8MHz with BSP430's default configuration.  BSP430 did not support XT2 until issue #24 was resolved.  With whatever release has that bug fixed (it's currently resolved in the next branch), you will need to add -DBSP430_PLATFORM_BOOT_CONFIGURE_XT2 to your build flags, or invoke iBSP430clockConfigureXT2_ni() explicitly.  The bootstrap/clocks example will show what's going on, specifically whether the crystal is faulted (assuming it was configured).

BTW: The crystal frequency is 4000000Hz, not 2^22 Hz.  The exp430f5529 platform will define BSP430_CLOCK_NOMINAL_XT2CLK_HZ correctly in the referenced release.
